class_name GlobalConstants

# -- Data paths --
const ITEMS_LIST_JSON_PATH: String = "res://raw_data/item_list.json"
const LOG_FILE_DEBUG: String = "user://log.txt"

# == WORLD GENERATION PROPERTIES ==

# Function enable/disable
const WORLDGEN_ENABLE_ENSURE_MINIMUN_COMMON_ROOMS: bool = true
const WORLDGEN_ENABLE_ENSURE_INSTANCES_RANGE: bool = true
const WORLDGEN_ENABLE_PLACE_BOSS_ROOM: bool = true
const WORLDGEN_ENABLE_PLACE_SPECIAL_ROOMS: bool = true
const WORLDGEN_ENABLE_PLACE_TREASURE_ROOM: bool = true
const WORLDGEN_ENABLE_PLACE_SHOP_ROOM: bool = true
const WORLDGEN_ENABLE_PLACE_CAMPUS_ROOM: bool = true
const WORLDGEN_ENABLE_CONNECT_CORRIDORS_TO_ADJACENT: bool = true
const WORLDGEN_ENABLE_CLEAN_ISOLATED_CORRIDORS: bool = true
const WORLDGEN_ENABLE_EXPAND_DEAD_CORRIDORS:bool = false
const WORLDGEN_ENABLE_POPULATE_BRANCHES: bool = true
const WORLDGEN_ENABLE_GENERATE_SECUNDARY_BRANCHES: bool = true

# -- Base length of the main path from initial room --
const WORLDGEN_MAX_LENGTH_FROM_INIT: int = 50

# -- Additional length per level --
const WORLDGEN_MAX_LENGTH_LEVEL_MULTLIPIER: int = 100


const WORLDGEN_MAX_INSTANCES_PER_POPULATION: int = 3
const WORLDGEN_MAX_TARGET_SECUNDARY_BRANCH: int = 3

# -- Main path verticality --
const WORLDGEN_MAX_VERTICAL_CORRIDORS: int = 4
const WORLDGEN_VERTICAL_CORRIDOR_TURN_CHANCE: float = 0.4

# -- Branches --
const WORLDGEN_BRANCHING_ROOM_CHANCE: float = 0.4
const WORLDGEN_BRANCH_LENGTH_MIN: int = 2
const WORLDGEN_BRANCH_LENGTH_MAX: int = 5
const WORLDGEN_MAX_BACKTRACK_ATTEMPTS: int = 4

# -- Rooms --
const WORLDGEN_MIN_COMMON_ROOMS_PER_LEVEL: int = 25


# -- Special rooms --
const WORLDGEN_MAX_TREASURE_ROOMS_PER_LEVEL: int = 4
const WORLDGEN_MAX_SHOP_ROOMS_PER_LEVEL: int = 2
const WORLDGEN_CAMPUS_ROOM_CHANCE: float = 1
const WORLDGEN_MAX_BOSS_ATTEMPTS = 15


# == ENTITY GENERATION ==

# -- HP RANGE --
const ENTTITYGEN_MIN_RANDOM_HP: int = 50
const ENTTITYGEN_MAX_RANDOM_HP: int = 200

# -- PHYSIC DAMAGE RANGE --
const ENTTITYGEN_MIN_RANDOM_PHY_DMG: int = 10
const ENTTITYGEN_MAX_RANDOM_PHY_DMG: int = 30

# -- MAGIC DAMAGE RANGE --
const ENTTITYGEN_MIN_RANDOM_MAG_DMG: int = 30
const ENTTITYGEN_MAX_RANDOM_MAG_DMG: int = 50

# -- PHYSIC ARMOR RANGE --
const ENTTITYGEN_MIN_RANDOM_PHY_ARM: int = 5
const ENTTITYGEN_MAX_RANDOM_PHY_ARM: int = 50

# -- MAGIC ARMOR RANGE --
const ENTTITYGEN_MIN_RANDOM_MAG_ARM: int = 5
const ENTTITYGEN_MAX_RANDOM_MAG_ARM: int = 50

# -- PHYSIC PENETRATION RANGE --
const ENTTITYGEN_MIN_RANDOM_PHY_PEN: int = 5
const ENTTITYGEN_MAX_RANDOM_PHY_PEN: int = 50

# -- MAGIC PENETRATION RANGE --
const ENTTITYGEN_MIN_RANDOM_MAG_PEN: int = 10
const ENTTITYGEN_MAX_RANDOM_MAG_PEN: int = 60

# -- ATTACK SPEED RANGE --
const ENTTITYGEN_MIN_RANDOM_ATK_SPD: int = 1
const ENTTITYGEN_MAX_RANDOM_ATK_SPD: int = 2

# -- ATTACK SPEED RANGE --
const ENTTITYGEN_MIN_RANDOM_TRU_DMG: int = 10
const ENTTITYGEN_MAX_RANDOM_TRU_DMG: int = 20

# -- Debug --
const WORLDGEN_DEBUG_DEFAULT_SEED: int = 72139486
