class_name GlobalConstants

# -- Debug --
const WORLDGEN_DEBUG_DEFAULT_SEED: int = 72139486

# -- API --
const API_URL_READ_MATCHES: String = "http://localhost/API_Rest/crud/read_partidas.php"

# -- Data paths --
const ITEMS_LIST_JSON_PATH: String = "res://raw_data/item_list.json"
const LOG_FILE_DEBUG: String = "user://log.txt"

# == COMBAT PROPERTIES ==

const COMBAT_TIME_BETWEEN_TURNS: float = 0
const COMBAT_TIME_BEFORE_CORPSE_DESPAWNS: float = 3

# == WORLD GENERATION PROPERTIES ==

# Function enable/disable
const WORLDGEN_ENABLE_ENSURE_MINIMUN_COMMON_ROOMS: bool = true
const WORLDGEN_ENABLE_ENSURE_INSTANCES_RANGE: bool = true
const WORLDGEN_ENABLE_PLACE_BOSS_ROOM: bool = true
const WORLDGEN_ENABLE_PLACE_SPECIAL_ROOMS: bool = true
const WORLDGEN_ENABLE_PLACE_TREASURE_ROOM: bool = true
const WORLDGEN_ENABLE_PLACE_SHOP_ROOM: bool = true
const WORLDGEN_ENABLE_PLACE_CAMPUS_ROOM: bool = true
const WORLDGEN_ENABLE_CONNECT_CORRIDORS_TO_ADJACENT: bool = true
const WORLDGEN_ENABLE_CLEAN_ISOLATED_CORRIDORS: bool = true
const WORLDGEN_ENABLE_EXPAND_DEAD_CORRIDORS:bool = false
const WORLDGEN_ENABLE_POPULATE_BRANCHES: bool = true
const WORLDGEN_ENABLE_GENERATE_SECUNDARY_BRANCHES: bool = true

# -- Base length of the main path from initial room --
const WORLDGEN_MAX_LENGTH_FROM_INIT: int = 50

# -- Additional length per level --
const WORLDGEN_MAX_LENGTH_LEVEL_MULTLIPIER: int = 100


const WORLDGEN_MAX_INSTANCES_PER_POPULATION: int = 3
const WORLDGEN_MAX_TARGET_SECUNDARY_BRANCH: int = 3

# -- Main path verticality --
const WORLDGEN_MAX_VERTICAL_CORRIDORS: int = 4
const WORLDGEN_VERTICAL_CORRIDOR_TURN_CHANCE: float = 0.4

# -- Branches --
const WORLDGEN_BRANCHING_ROOM_CHANCE: float = 0.4
const WORLDGEN_BRANCH_LENGTH_MIN: int = 2
const WORLDGEN_BRANCH_LENGTH_MAX: int = 5
const WORLDGEN_MAX_BACKTRACK_ATTEMPTS: int = 4

# -- Rooms --
const WORLDGEN_MIN_COMMON_ROOMS_PER_LEVEL: int = 25


# -- Special rooms --
const WORLDGEN_MAX_TREASURE_ROOMS_PER_LEVEL: int = 2
const WORLDGEN_MAX_SHOP_ROOMS_PER_LEVEL: int = 2
const WORLDGEN_CAMPUS_ROOM_CHANCE: float = 1
const WORLDGEN_MAX_BOSS_ATTEMPTS = 15


# == ENTITY GENERATION ==

# == INITIAL PLAYER STATS

const PLAYER_INITIAL_STAT_HEALTH_MAX: float = 200
const PLAYER_INITIAL_STAT_PHYSICAL_DAMAGE: float = 50
const PLAYER_INITIAL_STAT_PHYSICAL_PENETRATION: float = 0
const PLAYER_INITIAL_STAT_PHYSICAL_ARMOR: float = 8
const PLAYER_INITIAL_STAT_PHYSICAL_ATTACK_SPEED: float = 1
const PLAYER_INITIAL_STAT_MAGICAL_DAMAGE: float = 44
const PLAYER_INITIAL_STAT_MAGICAL_PENETRATION: float = 0
const PLAYER_INITIAL_STAT_MAGICAL_ARMOR: float = 12
const PLAYER_INITIAL_STAT_CRITICAL_CHANCE: float = 0

# == ATTACK & HABILITIES DAMAGES

const PLAYER_BASE_DMG_PHYSICAL_ATTACK: float = 20
const PLAYER_BASE_DMG_SKILL_PROJECTILE: float = 30
const PLAYER_BASE_DMG_SKILL_PILAR: float = 50
const PLAYER_BASE_DMG_SKILL_BELLS: float = 20
const PLAYER_BASE_HLT_SKILL_BELLS: float = 30
const PLAYER_BASE_DMG_SKILL_CAST: float = 20
const PLAYER_BASE_DMG_SKILL_RANDBALL: float = 20
const PLAYER_BASE_DMG_SKILL_SURIKEN: float = 40





# == ENEMY SKILLS BASE DAMAGE ==

const ENEMY_BASE_DMG_COMMON_ATTACK: float = 10

# == RANDOM ENEMY STAT RANGES

# -- HP RANGE --
const ENTTITYGEN_MIN_RANDOM_HP: int = 50
const ENTTITYGEN_MAX_RANDOM_HP: int = 100

# -- PHYSIC DAMAGE RANGE --
const ENTTITYGEN_MIN_RANDOM_PHY_DMG: int = 10
const ENTTITYGEN_MAX_RANDOM_PHY_DMG: int = 10

# -- MAGIC DAMAGE RANGE --
const ENTTITYGEN_MIN_RANDOM_MAG_DMG: int = 10
const ENTTITYGEN_MAX_RANDOM_MAG_DMG: int = 10

# -- PHYSIC ARMOR RANGE --
const ENTTITYGEN_MIN_RANDOM_PHY_ARM: int = 5
const ENTTITYGEN_MAX_RANDOM_PHY_ARM: int = 5

# -- MAGIC ARMOR RANGE --
const ENTTITYGEN_MIN_RANDOM_MAG_ARM: int = 5
const ENTTITYGEN_MAX_RANDOM_MAG_ARM: int = 5

# -- PHYSIC PENETRATION RANGE --
const ENTTITYGEN_MIN_RANDOM_PHY_PEN: int = 5
const ENTTITYGEN_MAX_RANDOM_PHY_PEN: int = 5

# -- MAGIC PENETRATION RANGE --
const ENTTITYGEN_MIN_RANDOM_MAG_PEN: int = 5
const ENTTITYGEN_MAX_RANDOM_MAG_PEN: int = 5

# -- ATTACK SPEED RANGE --
const ENTTITYGEN_MIN_RANDOM_ATK_SPD: int = 1
const ENTTITYGEN_MAX_RANDOM_ATK_SPD: int = 1

# -- TRUE DAMAGE RANGE --
const ENTTITYGEN_MIN_RANDOM_TRU_DMG: int = 0
const ENTTITYGEN_MAX_RANDOM_TRU_DMG: int = 0

# -- CRITIC CHANCE RANGE --
const ENTTITYGEN_MIN_RANDOM_CRI_CHA: int = 0
const ENTTITYGEN_MAX_RANDOM_CRI_CHA: int = 0





# == BOSS SKILLS BASE DAMAGE ==

# -- GORGON ATTACKS --
const BOSS_DMG_GORGON_ATTACK_1: float = 10
const BOSS_DMG_GORGON_ATTACK_2: float = 20
const BOSS_DMG_GORGON_ATTACK_3: float = 30

# -- MINOTAUR ATTACKS --
const BOSS_DMG_MINOTAUR_ATTACK_1: float = 20

# -- VAMPIRE ATTACKS --
const BOSS_DMG_VAMPIRE_ATTACK_1: float = 15

# -- WEREWOLF ATTACKS --
const BOSS_DMG_WEREWOLF_ATTACK_1: float = 30

# -- WIZARD 1 ATTACKS --
const BOSS_DMG_WIZARD_1_ATTACK_1: float = 10
const BOSS_DMG_WIZARD_1_ATTACK_2: float = 15
const BOSS_DMG_WIZARD_1_FLAME: float = 30
const BOSS_DMG_WIZARD_1_CHARGE: float = 25

# -- WIZARD 2 ATTACKS --
const BOSS_DMG_WIZARD_2_ATTACK_1: float = 20
const BOSS_DMG_WIZARD_2_ATTACK_2: float = 25
const BOSS_DMG_WIZARD_2_ARROW: float = 10
const BOSS_DMG_WIZARD_2_SPHERE: float = 25

# -- WIZARD 3 ATTACKS --
const BOSS_DMG_WIZARD_3_ATTACK_1: float = 10
const BOSS_DMG_WIZARD_3_CHARGE: float = 25
const BOSS_DMG_WIZARD_3_RAY: float = 40

# -- YOKAI ATTACKS --
const BOSS_DMG_YOKAI_ATTACK_1: float = 15
const BOSS_DMG_YOKAI_ATTACK_2: float = 50

# -- YOKAI 3 ATTACKS --
const BOSS_DMG_YOKAI_3_ATTACK_1: float = 25
const BOSS_DMG_YOKAI_3_ATTACK_2: float = 40
const BOSS_DMG_YOKAI_3_ATTACK_3: float = 35


# == RANDOM BOSS STAT RANGES

# -- HP RANGE --
const ENTTITYGEN_BOSS_MIN_RANDOM_HP: int = 200
const ENTTITYGEN_BOSS_MAX_RANDOM_HP: int = 400

# -- PHYSIC DAMAGE RANGE --
const ENTTITYGEN_BOSS_MIN_RANDOM_PHY_DMG: int = 20
const ENTTITYGEN_BOSS_MAX_RANDOM_PHY_DMG: int = 50

# -- MAGIC DAMAGE RANGE --
const ENTTITYGEN_BOSS_MIN_RANDOM_MAG_DMG: int = 20
const ENTTITYGEN_BOSS_MAX_RANDOM_MAG_DMG: int = 50

# -- PHYSIC ARMOR RANGE --
const ENTTITYGEN_BOSS_MIN_RANDOM_PHY_ARM: int = 20
const ENTTITYGEN_BOSS_MAX_RANDOM_PHY_ARM: int = 30

# -- MAGIC ARMOR RANGE --
const ENTTITYGEN_BOSS_MIN_RANDOM_MAG_ARM: int = 20
const ENTTITYGEN_BOSS_MAX_RANDOM_MAG_ARM: int = 30

# -- PHYSIC PENETRATION RANGE --
const ENTTITYGEN_BOSS_MIN_RANDOM_PHY_PEN: int = 5
const ENTTITYGEN_BOSS_MAX_RANDOM_PHY_PEN: int = 15

# -- MAGIC PENETRATION RANGE --
const ENTTITYGEN_BOSS_MIN_RANDOM_MAG_PEN: int = 5
const ENTTITYGEN_BOSS_MAX_RANDOM_MAG_PEN: int = 15

# -- ATTACK SPEED RANGE --
const ENTTITYGEN_BOSS_MIN_RANDOM_ATK_SPD: int = 1
const ENTTITYGEN_BOSS_MAX_RANDOM_ATK_SPD: int = 1

# -- TRUE DAMAGE RANGE --
const ENTTITYGEN_BOSS_MIN_RANDOM_TRU_DMG: int = 0
const ENTTITYGEN_BOSS_MAX_RANDOM_TRU_DMG: int = 0

# -- CRITIC CHANCE RANGE --
const ENTTITYGEN_BOSS_MIN_RANDOM_CRI_CHA: int = 0
const ENTTITYGEN_BOSS_MAX_RANDOM_CRI_CHA: int = 25


# == KEY ITEMS STATS ==

const KEY_ITEM_0_HP_PERCENTAGE_TO_HEAL: float = 5
const KEY_ITEM_1_HP_PERCENTAGE_TO_HEAL: float = 10
const KEY_ITEM_2_HP_PERCENTAGE_TO_HEAL: float = 25
const KEY_ITEM_3_HP_PERCENTAGE_TO_HEAL: float = 45
const KEY_ITEM_4_HP_PERCENTAGE_TO_HEAL: float = 25
const KEY_ITEM_5_HP_PERCENTAGE_TO_HEAL: float = 5
const KEY_ITEM_6_HP_PERCENTAGE_TO_HEAL: float = 30
const KEY_ITEM_6_PHY_DMG_PERCENTAGE_DOWN_TEMP: float = 15
const KEY_ITEM_7_HP_PERCENTAGE_TO_HEAL: float = 15
const KEY_ITEM_7_PHY_DMG_PERCENTAGE_DOWN_TEMP: float = 10
const KEY_ITEM_8_HP_PERCENTAGE_TO_HEAL: float = 15
const KEY_ITEM_8_MAG_DMG_PERCENTAGE_DOWN_TEMP: float = 5
const KEY_ITEM_9_MAG_ARM_UP: float = 5
const KEY_ITEM_10_PHY_ARM_UP: float = 5
const KEY_ITEM_11_MAG_ARM_UP: float = 10
const KEY_ITEM_12_PHY_ARM_UP: float = 10
const KEY_ITEM_13_HP_TO_HEAL: float = 100
const KEY_ITEM_13_CRI_CHA_PERCENTAGE_DOWN: float = 4
const KEY_ITEM_14_HP_MAX_PERCENTAGE_DOWN_UP: float = 15
const KEY_ITEM_15_HP_PERCENTAGE_TO_HEAL: float = 25
const KEY_ITEM_15_POISON_CHANCE: float = 10
const KEY_ITEM_15_POISON_MAX_HP_PERCENTAGE: float = 30
const KEY_ITEM_16_HP_PERCENTAGE_TO_HEAL: float = 35
const KEY_ITEM_16_POISON_CHANCE: float = 10
const KEY_ITEM_16_POISON_MAX_HP_PERCENTAGE: float = 50
const KEY_ITEM_17_HP_PERCENTAGE_TO_HEAL: float = 50
const KEY_ITEM_17_POISON_CHANCE: float = 10
const KEY_ITEM_17_POISON_MAX_HP_PERCENTAGE: float = 75
const KEY_ITEM_18_HP_PERCENTAGE_TO_HEAL: float = 5
const KEY_ITEM_18_POISON_CHANCE: float = 10
const KEY_ITEM_18_POISON_MAX_HP_PERCENTAGE: float = 10
const KEY_ITEM_19_HP_MAX_UP: float = 50
const KEY_ITEM_20_MIN_GOLD_RANGE: float = 10
const KEY_ITEM_20_MAX_GOLD_RANGE: float = 100
const KEY_ITEM_21_LOSE_CHANCE: float = 1
const KEY_ITEM_22_GOLD_GIVEN: float = 10
const KEY_ITEM_23_GOLD_GIVEN: float = 50
const KEY_ITEM_24_GOLD_GIVEN: float = 100
const KEY_ITEM_25_GOLD_GIVEN: float = 10
const KEY_ITEM_25_KEYS_GIVEN: float = 3
const KEY_ITEM_26_PHY_DMG_PERCENTAGE_UP_TEMP: float = 50
const KEY_ITEM_27_PHY_ARM_PERCENTAGE_UP_TEMP: float = 50
const KEY_ITEM_28_MAG_DMG_PERCENTAGE_UP_TEMP: float = 50
const KEY_ITEM_29_MAG_ARM_PERCENTAGE_UP_TEMP: float = 50
const KEY_ITEM_31_HP_MAX_PERCENTAGE_UP_TEMP: float = 50
const KEY_ITEM_33_CRI_CHA_UP: float = 50
const KEY_ITEM_34_RANDOM_STAT_UP: float = 44
